version: '3'

services:
  todolist:
    image: deigosiahaan/todolist
    container_name: todolist
    build: .
    volumes:
      - .:/app
    ports:
      - "3030:3030"
    command: go run cmd/main.go
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: brengsek96
      MYSQL_DATABASE: todolist
      MYSQL_USER: project
      MYSQL_PASSWORD: brengsek96
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
